name: Cypress-Cucumber Tests
on:
    push:
        branches: [master]
jobs:
    Run_test:
        runs-on: windows-latest
        strategy:
            matrix:
                node-version: [14.17.0]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - name: update node manager
              run: npm i npm@latest
            - name: install all dependencies
              run: npm i
            - name: Install Cypress
              run: npm install cypress
            - name: run test and create report
              run: npm run cypress:run 

            - name: Upload artifact mochawesome-reporter
              uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: mochawesome-reporter
                  path: ./cypress/reports/
                  retention-days: 5 
            - name: Deploy to pages
              if: always()
              uses: peaceiris/actions-gh-pages@v3.7.3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_branch: gh-pages
                  publish_dir: ./cypress/reports/