name: Cypress-Cucumber Tests
on:
    push:
        branches: [master]
jobs:
    Run_test:
        runs-on: windows-latest
        strategy:
            matrix:
                node-version: [14.17.0]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - name: update node manager
              run: npm i npm@latest
            - name: install all dependencies
              run: npm i
            - name: Install Cypress
              run: npm install cypress
            - name: Install reporter 
              run: npm i --save-dev cypress-mochawesome-reporter
            - name: run test
              run: npm run cypress:run:hub 
