name: Cypress Tests 
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm ci
    - name: Install cypress-mochawesome-reporter
      run: npm i --save-dev cypress-mochawesome-reporter
    - name: Run cypress tests
      run: npm run cypress:run 
    - uses: actions/upload-artifact@master
      with:
        name: mochawesome-reporter
        path: mochawesome-reporter
        retention-days: 20
  
    - name: Get report history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
          ref: gh-pages
          path: gh-pages

    - name: Mochawesome reporter action from tests
      uses: simple-elf/Mochawesome-report-action@master
      if: always()

      with:
          reports: reports
          gh_pages: gh-pages
          reports: reports
          reports: reports
          keep_reports: 20

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: Mochawesome-report